# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SPIVAE',
                'doc_host': 'https://GabrielFernandezFernandez.github.io',
                'git_url': 'https://github.com/GabrielFernandezFernandez/SPIVAE',
                'lib_path': 'SPIVAE'},
  'syms': {'SPIVAE.core': {'SPIVAE.core.foo': ('core.html#foo', 'SPIVAE/core.py')}}}
