# Model training on FBM


<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

In this tutorial, we aim at training SPIVAE with the dataset of
fractional Brownian motion (FBM) to extract the generalized diffusion
coefficient *D*, and the anomalous exponent *α*.

To train the models, we use the [fastai](https://docs.fast.ai/) library
that provides easy to use methods. First, we gather everything needed to
train (the data, the model, the loss, the optimizer, the callbacks, and
metrics) into a `Learner` object. We will use the `Learner` to hold all
the parameters and handle the training procedure.

<div>

<figure class=''>

<div>

<img src="0_training_FBM_files/figure-commonmark/mermaid-figure-1.png"
style="width:11.34in;height:6.96in" />

</div>

</figure>

</div>

# Setup

We start selecting the parameters of the device to train on, the
dataset, and the model.

``` python
DEVICE= 'cpu'  # 'cuda'
print(DEVICE)
```

    cpu

## Data

To construct the dataset of FBM, we vary *D* logarithmically inside the
range 10<sup>−5</sup> and 10<sup>−2</sup> such that the displacements
are smaller than one. At the same time, we choose *α* ∈ \[0.2, 1.8\]. We
take the same amount of trajectories for each combination of parameters,
about 100 thousand trajectories in total. We split them in training and
validation sets, and select a batch size `bs`.

``` python
Ds = np.geomspace(1e-5,1e-2, 10)
alphas = np.linspace(0.2,1.8,21)
n_alphas, n_Ds = len(alphas), len(Ds)
ds_args = dict(path="../../data/raw/", model='fbm', # 'sbm'
               N=2, # small dataset for testing
               # N=int(100_000/n_alphas/n_Ds),
               T=400,
               D=Ds, alpha=alphas,
               N_save=100, # small dataset for testing
               # N_save=6_000,
               T_save=400,
               seed=0, valid_pct=0.2, bs=2**8,)
```

``` python
ds_args.update(dict(N=N=int(100_000/n_alphas/n_Ds), N_save=6_000))
```

We generate training data as explained in the [data
docs](../source/data.html#fractional-brownian-motion). You can skip this
step if you already generated data using the data generation notebook.

``` python
dataset = AD.create_dataset(T=ds_args["T"], N_models=ds_args["N"],
                            exponents=ds_args["alpha"],
                            dimension=1, models=[2],  # fbm
                            T_save=ds_args["T_save"], N_save=ds_args["N_save"],
                            save_trajectories=True, path="../../data/raw/")
```

We create the data loaders `dls` for training and validation with the
parameters we selected above.

``` python
dls = load_data(ds_args).to(DEVICE)
dls[1].drop_last = True # for validation to throw the last incomplete batch or not
dls[0].drop_last, dls[1].drop_last, dls[1].bs, dls.device
```

    (True, True, 256, 'cpu')

## Model

We set a small model to train rapidly, but large enough to provide
adequate expressiveness. We fix 6 latent neurons, as a priori, we do not
know how many neurons will encode the trajectory parameters.

``` python
model_args = dict(# VAE #################
                  o_dim=ds_args['T']-1,
                  nc_in=1,  # 1D
                  nc_out=6, # = z_dim
                  nf=[16]*4,
                  avg_size=16,
                  encoder=[200,100],
                  z_dim=6,  # latent dimension
                  decoder=[100,200],
                  beta=0,
                  # WaveNet ############
                  in_channels=1,
                  res_channels=16,skip_channels=16,
                  c_channels=6, # = nc_out
                  g_channels=0,
                  res_kernel_size=3,
                  layer_size=4,  # 6  # Largest dilation is 2**layer_size
                  stack_size=1,
                  out_distribution= "Normal",
                  num_mixtures=1,
                  use_pad=False,
                  model_name = 'SPIVAE',
                 )
```

We instantiate a model and check the forward pass works for a random
batch.

``` python
model = VAEWaveNet(**model_args).to(DEVICE)
print('RF:', model.receptive_field, 'bs:', dls.bs)
x,y=b = dls.one_batch(); t = model(x)
```

## Loss

We define the loss function as defined in [Utils](../source/utils.html).
The initial loss for this dataset is around 1.5, bigger than that the
initialization provides an unstable model that may not train properly.

``` python
loss_fn = Loss(model.receptive_field, model.c_channels,
                    beta=model_args['beta'], reduction='mean')
l = loss_fn(t,y).item();
print('Initial loss: ',l)
assert l<1.5, 'Initial loss should be around 1.5 or less'
```

    RF: 32 bs: 256
    Initial loss:  0.9456117153167725

## Callbacks

We now set a few callback functions to show relevant information during
training. The first two update a plot of the total loss for training and
validation, and the Kullback-Leibler divergence (*D*<sub>*K**L*</sub>)
of the latent neurons, respectively. The other two record the
reconstruction loss and the *D*<sub>*K**L*</sub> of each latent neuron.

``` python
callbacks = [ShowLossCallback(), ShowKLDsCallback(),
             GMsCallback(model.receptive_field,model.c_channels),
             KLDsCallback(model.c_channels)]
```

## Metrics

We add two metrics to follow the reconstruction loss and the divergence
term in a table at each epoch of the training.

``` python
metrics = [GaussianMixtureMetric(model.receptive_field, model.c_channels,reduction='mean'),
           KLDMetric(model.c_channels,),
          ]
```

# Learner

With all the ingredients, we create the `Learner` with the default
optimizer, Adam.

``` python
learn = Learner(dls, model, loss_func=loss_fn, opt_func=Adam, cbs=callbacks, metrics=metrics,)
if torch.cuda.is_available() and DEVICE=='cuda': learn.model.cuda()
```

The learner can show us a summary including the model sizes and number
of parameters.

``` python
learn.summary()
```

<style>
    /* Turns off some styling */
    progress {
        /* gets rid of default border in Firefox and Opera. */
        border: none;
        /* Needs to be in here for Safari polyfill so background images work as expected. */
        background-size: auto;
    }
    progress:not([value]), progress:not([value])::-webkit-progress-bar {
        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);
    }
    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {
        background: #F44336;
    }
</style>

    VAEWaveNet (Input shape: 256 x 1 x 399)
    ============================================================================
    Layer (type)         Output Shape         Param #    Trainable 
    ============================================================================
                         256 x 16 x 397      
    Conv1d                                    64         True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 16 x 395      
    Conv1d                                    784        True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 16 x 393      
    Conv1d                                    784        True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 16 x 391      
    Conv1d                                    784        True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 16 x 16       
    AdaptiveAvgPool1d                                              
    AdaptiveMaxPool1d                                              
    ____________________________________________________________________________
                         256 x 512           
    View                                                           
    ____________________________________________________________________________
                         256 x 200           
    Linear                                    102600     True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 100           
    Linear                                    20100      True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 12            
    Linear                                    1212       True      
    ____________________________________________________________________________
                         256 x 100           
    Linear                                    700        True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 200           
    Linear                                    20200      True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 512           
    Linear                                    102912     True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 16 x 32       
    View                                                           
    ____________________________________________________________________________
                         256 x 16 x 393      
    ConvTranspose1d                           784        True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 16 x 395      
    ConvTranspose1d                           784        True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 16 x 397      
    ConvTranspose1d                           784        True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 6 x 399       
    ConvTranspose1d                           294        True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 16 x 399      
    Conv1d                                    32         True      
    ____________________________________________________________________________
                         256 x 16 x 397      
    Conv1d                                    528        True      
    ____________________________________________________________________________
                         256 x 32 x 395      
    Conv1d                                    1568       True      
    ____________________________________________________________________________
                         256 x 32 x 399      
    Conv1d                                    192        True      
    Conv1d                                    272        True      
    Conv1d                                    272        True      
    ____________________________________________________________________________
                         256 x 32 x 391      
    Conv1d                                    1568       True      
    ____________________________________________________________________________
                         256 x 32 x 399      
    Conv1d                                    192        True      
    Conv1d                                    272        True      
    Conv1d                                    272        True      
    ____________________________________________________________________________
                         256 x 32 x 383      
    Conv1d                                    1568       True      
    ____________________________________________________________________________
                         256 x 32 x 399      
    Conv1d                                    192        True      
    Conv1d                                    272        True      
    Conv1d                                    272        True      
    ____________________________________________________________________________
                         256 x 32 x 367      
    Conv1d                                    1568       True      
    ____________________________________________________________________________
                         256 x 32 x 399      
    Conv1d                                    192        True      
    Conv1d                                    272        True      
    Conv1d                                    272        True      
    ReLU                                                           
    Conv1d                                    272        True      
    ReLU                                                           
    ____________________________________________________________________________
                         256 x 3 x 367       
    Conv1d                                    51         True      
    ____________________________________________________________________________

    Total params: 262,885
    Total trainable params: 262,885
    Total non-trainable params: 0

    Optimizer used: <function Adam>
    Loss function: <SPIVAE.utils.Loss object>

    Callbacks:
      - TrainEvalCallback
      - CastToTensor
      - Recorder
      - ProgressCallback
      - ShowLossCallback
      - ShowKLDsCallback
      - GMsCallback
      - KLDsCallback

## Learning rate finder

Finally, we need a learning rate. Conveniently,
[fastai](https://docs.fast.ai/) includes a [learning rate
finder](https://docs.fast.ai/callback.schedule.html#learner.lr_find).
This finder can suggest some points, each based on a criterion that
guides us. Hence, we try with one order above and below the default
criterion, the
[valley](https://docs.fast.ai/callback.schedule.html#valley).

``` python
learn.lr_find()
```

<style>
    /* Turns off some styling */
    progress {
        /* gets rid of default border in Firefox and Opera. */
        border: none;
        /* Needs to be in here for Safari polyfill so background images work as expected. */
        background-size: auto;
    }
    progress:not([value]), progress:not([value])::-webkit-progress-bar {
        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);
    }
    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {
        background: #F44336;
    }
</style>

    SuggestedLRs(valley=9.120108734350652e-05)

![](0_training_FBM_files/figure-commonmark/cell-14-output-4.png)

The valley is around 10<sup>−4</sup>, thus we will start trying a
learning rate of 10<sup>−3</sup> to see if we can learn fast.

During the search, not only the loss was logged but also the
*D*<sub>*K**L*</sub> (thanks to the callback), which we can see here:

``` python
plt.semilogy(np.stack(learn.kl_ds.preds)); learn.kl_ds.preds=[]
```

![](0_training_FBM_files/figure-commonmark/cell-15-output-1.png)

During the training, we will keep an eye on both the total loss and the
*D*<sub>*K**L*</sub>.

# Training with *β*=0

We start training with *β* = 0 to have no additional constraint in the
latent neurons and allow the VAE to use the full capacity of its
bottleneck.

``` python
learn.loss_func.beta=0
```

To ease the training, we update the model’s parameters following the
learning rate schedule developed by [Leslie N. Smith et
al. (2017)](https://arxiv.org/abs/1708.07120) and already implemented in
[fastai](https://docs.fast.ai/callback.schedule.html#learner.fit_one_cycle).
We choose as the maximum learning rate the one derived from the finder
above.

``` python
E=64
```

``` python
learn.fit_one_cycle(E, lr_max=1e-3,)
```

<style>
    /* Turns off some styling */
    progress {
        /* gets rid of default border in Firefox and Opera. */
        border: none;
        /* Needs to be in here for Safari polyfill so background images work as expected. */
        background-size: auto;
    }
    progress:not([value]), progress:not([value])::-webkit-progress-bar {
        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);
    }
    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {
        background: #F44336;
    }
</style>

<table class="dataframe" data-quarto-postprocess="true" data-border="1">
<thead>
<tr style="text-align: left;">
<th data-quarto-table-cell-role="th">epoch</th>
<th data-quarto-table-cell-role="th">train_loss</th>
<th data-quarto-table-cell-role="th">valid_loss</th>
<th data-quarto-table-cell-role="th">mix_gaussian_loss</th>
<th data-quarto-table-cell-role="th">kld</th>
<th data-quarto-table-cell-role="th">time</th>
</tr>
</thead>
<tbody>
<tr>
<td>0</td>
<td>-1.315952</td>
<td>-1.661407</td>
<td>-1.661407</td>
<td>19.406342</td>
<td>01:09</td>
</tr>
<tr>
<td>1</td>
<td>-2.112537</td>
<td>-2.151353</td>
<td>-2.151353</td>
<td>64.277298</td>
<td>01:10</td>
</tr>
<tr>
<td>2</td>
<td>-2.239122</td>
<td>-2.249071</td>
<td>-2.249071</td>
<td>86.196838</td>
<td>01:11</td>
</tr>
<tr>
<td>3</td>
<td>-2.244182</td>
<td>-2.256283</td>
<td>-2.256283</td>
<td>78.044266</td>
<td>01:10</td>
</tr>
<tr>
<td>4</td>
<td>-2.238847</td>
<td>-2.265728</td>
<td>-2.265728</td>
<td>79.355087</td>
<td>01:10</td>
</tr>
<tr>
<td>5</td>
<td>-2.185477</td>
<td>-2.220979</td>
<td>-2.220979</td>
<td>73.193192</td>
<td>01:11</td>
</tr>
<tr>
<td>6</td>
<td>-2.157342</td>
<td>-2.245884</td>
<td>-2.245884</td>
<td>68.523232</td>
<td>01:11</td>
</tr>
<tr>
<td>7</td>
<td>-2.011828</td>
<td>-2.076498</td>
<td>-2.076498</td>
<td>48.271271</td>
<td>01:10</td>
</tr>
<tr>
<td>8</td>
<td>-2.026002</td>
<td>-2.205460</td>
<td>-2.205460</td>
<td>14.866062</td>
<td>01:10</td>
</tr>
<tr>
<td>9</td>
<td>-2.146519</td>
<td>-2.218804</td>
<td>-2.218804</td>
<td>27.197741</td>
<td>01:12</td>
</tr>
<tr>
<td>10</td>
<td>-2.164488</td>
<td>-2.268744</td>
<td>-2.268744</td>
<td>53.392033</td>
<td>01:11</td>
</tr>
<tr>
<td>11</td>
<td>-2.094013</td>
<td>-2.184355</td>
<td>-2.184355</td>
<td>72.369965</td>
<td>01:10</td>
</tr>
<tr>
<td>12</td>
<td>-2.228285</td>
<td>-2.122396</td>
<td>-2.122396</td>
<td>162.265594</td>
<td>01:10</td>
</tr>
<tr>
<td>13</td>
<td>-2.266493</td>
<td>-2.289713</td>
<td>-2.289713</td>
<td>189.916687</td>
<td>01:10</td>
</tr>
<tr>
<td>14</td>
<td>-2.229059</td>
<td>-1.878625</td>
<td>-1.878625</td>
<td>314.366608</td>
<td>01:11</td>
</tr>
<tr>
<td>15</td>
<td>-2.244426</td>
<td>-2.255815</td>
<td>-2.255815</td>
<td>336.166351</td>
<td>01:10</td>
</tr>
<tr>
<td>16</td>
<td>-2.272467</td>
<td>-2.274356</td>
<td>-2.274356</td>
<td>377.487793</td>
<td>01:11</td>
</tr>
<tr>
<td>17</td>
<td>-2.277053</td>
<td>-2.275987</td>
<td>-2.275987</td>
<td>417.207703</td>
<td>01:10</td>
</tr>
<tr>
<td>18</td>
<td>-2.269186</td>
<td>-2.246015</td>
<td>-2.246015</td>
<td>479.375000</td>
<td>01:11</td>
</tr>
<tr>
<td>19</td>
<td>-2.293643</td>
<td>-2.303562</td>
<td>-2.303562</td>
<td>493.494781</td>
<td>01:10</td>
</tr>
<tr>
<td>20</td>
<td>-2.299952</td>
<td>-2.314991</td>
<td>-2.314991</td>
<td>547.708008</td>
<td>01:10</td>
</tr>
<tr>
<td>21</td>
<td>-2.322182</td>
<td>-2.281061</td>
<td>-2.281061</td>
<td>568.945740</td>
<td>01:10</td>
</tr>
<tr>
<td>22</td>
<td>-2.310960</td>
<td>-2.320824</td>
<td>-2.320824</td>
<td>608.434265</td>
<td>01:10</td>
</tr>
<tr>
<td>23</td>
<td>-2.315642</td>
<td>-2.324992</td>
<td>-2.324992</td>
<td>607.956360</td>
<td>01:11</td>
</tr>
<tr>
<td>24</td>
<td>-2.332518</td>
<td>-2.312339</td>
<td>-2.312339</td>
<td>635.526489</td>
<td>01:11</td>
</tr>
<tr>
<td>25</td>
<td>-2.317588</td>
<td>-2.331322</td>
<td>-2.331322</td>
<td>659.979919</td>
<td>01:10</td>
</tr>
<tr>
<td>26</td>
<td>-2.326688</td>
<td>-2.328422</td>
<td>-2.328422</td>
<td>651.702820</td>
<td>01:11</td>
</tr>
<tr>
<td>27</td>
<td>-2.339881</td>
<td>-2.334195</td>
<td>-2.334195</td>
<td>681.555664</td>
<td>01:11</td>
</tr>
<tr>
<td>28</td>
<td>-2.329673</td>
<td>-2.333597</td>
<td>-2.333597</td>
<td>717.498901</td>
<td>01:10</td>
</tr>
<tr>
<td>29</td>
<td>-2.340475</td>
<td>-2.333066</td>
<td>-2.333066</td>
<td>720.397827</td>
<td>01:10</td>
</tr>
<tr>
<td>30</td>
<td>-2.338010</td>
<td>-2.337913</td>
<td>-2.337913</td>
<td>755.900269</td>
<td>01:11</td>
</tr>
<tr>
<td>31</td>
<td>-2.332206</td>
<td>-2.332510</td>
<td>-2.332510</td>
<td>756.721130</td>
<td>01:12</td>
</tr>
<tr>
<td>32</td>
<td>-2.351339</td>
<td>-2.338526</td>
<td>-2.338526</td>
<td>782.172852</td>
<td>01:11</td>
</tr>
<tr>
<td>33</td>
<td>-2.340485</td>
<td>-2.338783</td>
<td>-2.338783</td>
<td>805.748047</td>
<td>01:11</td>
</tr>
<tr>
<td>34</td>
<td>-2.340624</td>
<td>-2.342476</td>
<td>-2.342476</td>
<td>810.832153</td>
<td>01:13</td>
</tr>
<tr>
<td>35</td>
<td>-2.343892</td>
<td>-2.342334</td>
<td>-2.342334</td>
<td>830.463257</td>
<td>01:11</td>
</tr>
<tr>
<td>36</td>
<td>-2.348852</td>
<td>-2.345546</td>
<td>-2.345546</td>
<td>821.223083</td>
<td>01:11</td>
</tr>
<tr>
<td>37</td>
<td>-2.355019</td>
<td>-2.345020</td>
<td>-2.345020</td>
<td>839.597351</td>
<td>01:11</td>
</tr>
<tr>
<td>38</td>
<td>-2.345042</td>
<td>-2.346593</td>
<td>-2.346593</td>
<td>839.534668</td>
<td>01:11</td>
</tr>
<tr>
<td>39</td>
<td>-2.355663</td>
<td>-2.346778</td>
<td>-2.346778</td>
<td>839.826233</td>
<td>01:12</td>
</tr>
<tr>
<td>40</td>
<td>-2.342772</td>
<td>-2.347796</td>
<td>-2.347796</td>
<td>840.443481</td>
<td>01:11</td>
</tr>
<tr>
<td>41</td>
<td>-2.358884</td>
<td>-2.348896</td>
<td>-2.348896</td>
<td>830.699219</td>
<td>01:11</td>
</tr>
<tr>
<td>42</td>
<td>-2.349423</td>
<td>-2.349129</td>
<td>-2.349129</td>
<td>840.666992</td>
<td>01:11</td>
</tr>
<tr>
<td>43</td>
<td>-2.348464</td>
<td>-2.346027</td>
<td>-2.346027</td>
<td>832.678467</td>
<td>01:12</td>
</tr>
<tr>
<td>44</td>
<td>-2.352715</td>
<td>-2.349886</td>
<td>-2.349886</td>
<td>834.427307</td>
<td>01:11</td>
</tr>
<tr>
<td>45</td>
<td>-2.344991</td>
<td>-2.349920</td>
<td>-2.349920</td>
<td>826.926025</td>
<td>01:11</td>
</tr>
<tr>
<td>46</td>
<td>-2.341416</td>
<td>-2.350274</td>
<td>-2.350274</td>
<td>831.225464</td>
<td>01:11</td>
</tr>
<tr>
<td>47</td>
<td>-2.350832</td>
<td>-2.350190</td>
<td>-2.350190</td>
<td>828.069336</td>
<td>01:12</td>
</tr>
<tr>
<td>48</td>
<td>-2.345083</td>
<td>-2.350618</td>
<td>-2.350618</td>
<td>826.633118</td>
<td>01:12</td>
</tr>
<tr>
<td>49</td>
<td>-2.360827</td>
<td>-2.350861</td>
<td>-2.350861</td>
<td>821.838623</td>
<td>01:11</td>
</tr>
<tr>
<td>50</td>
<td>-2.352463</td>
<td>-2.350962</td>
<td>-2.350962</td>
<td>830.453674</td>
<td>01:12</td>
</tr>
<tr>
<td>51</td>
<td>-2.347570</td>
<td>-2.351095</td>
<td>-2.351095</td>
<td>823.741089</td>
<td>01:12</td>
</tr>
<tr>
<td>52</td>
<td>-2.360364</td>
<td>-2.351196</td>
<td>-2.351196</td>
<td>821.325806</td>
<td>01:12</td>
</tr>
<tr>
<td>53</td>
<td>-2.343230</td>
<td>-2.351074</td>
<td>-2.351074</td>
<td>823.521729</td>
<td>01:11</td>
</tr>
<tr>
<td>54</td>
<td>-2.355769</td>
<td>-2.351494</td>
<td>-2.351494</td>
<td>821.793335</td>
<td>01:12</td>
</tr>
<tr>
<td>55</td>
<td>-2.358197</td>
<td>-2.351494</td>
<td>-2.351494</td>
<td>817.322815</td>
<td>01:12</td>
</tr>
<tr>
<td>56</td>
<td>-2.359900</td>
<td>-2.351530</td>
<td>-2.351530</td>
<td>815.922485</td>
<td>01:12</td>
</tr>
<tr>
<td>57</td>
<td>-2.349110</td>
<td>-2.351698</td>
<td>-2.351698</td>
<td>814.793518</td>
<td>01:11</td>
</tr>
<tr>
<td>58</td>
<td>-2.355841</td>
<td>-2.351716</td>
<td>-2.351716</td>
<td>815.463562</td>
<td>01:11</td>
</tr>
<tr>
<td>59</td>
<td>-2.358056</td>
<td>-2.351770</td>
<td>-2.351770</td>
<td>813.260559</td>
<td>01:15</td>
</tr>
<tr>
<td>60</td>
<td>-2.354583</td>
<td>-2.351813</td>
<td>-2.351813</td>
<td>811.844543</td>
<td>01:12</td>
</tr>
<tr>
<td>61</td>
<td>-2.344743</td>
<td>-2.351826</td>
<td>-2.351826</td>
<td>812.462219</td>
<td>01:13</td>
</tr>
<tr>
<td>62</td>
<td>-2.350585</td>
<td>-2.351825</td>
<td>-2.351825</td>
<td>812.875671</td>
<td>01:12</td>
</tr>
<tr>
<td>63</td>
<td>-2.355194</td>
<td>-2.351831</td>
<td>-2.351831</td>
<td>812.403564</td>
<td>01:12</td>
</tr>
</tbody>
</table>

![](0_training_FBM_files/figure-commonmark/cell-18-output-3.png)

![](0_training_FBM_files/figure-commonmark/cell-18-output-4.png)

After training, we see a validation loss around -2.35 and two neurons
that contribute the most to the *D*<sub>*K**L*</sub>. We take a
checkpoint of the model at this moment.

``` python
model_name = 'fbm' + f'_E{E}'
if not os.path.exists("./models/"+model_name+'.tar'):
    save_model("./models/"+model_name, model, model_args, ds_args)
```

    Saved at ./models/fbm_E64.tar

``` python
plt.semilogy(np.stack(learn.kl_ds.preds));
```

![](0_training_FBM_files/figure-commonmark/cell-20-output-1.png)

``` python
# se the actual learning rates and momentums set during this training cycle
lrs,moms = learn.recorder.hps['lr'],learn.recorder.hps['mom']
plt.plot(lrs);plt.plot(moms);
```

# Annealing *β*

Now, we increase *β* to impose a Gaussian prior into the latent neurons
distribution which effectively forces the encoding of the already
present information to use the minimal number of neurons while noising
out the rest of neurons.

``` python
E=64
```

``` python
model_name = 'fbm' + f'_E{E}'
c_point, model = load_checkpoint("./models/"+model_name,device=DEVICE)
```

``` python
learn.loss_func.beta=1e-4; model_args.update(dict(beta=1e-4))
```

``` python
E=16
```

``` python
learn.fit_one_cycle(E, lr_max=1e-3,)
```

<style>
    /* Turns off some styling */
    progress {
        /* gets rid of default border in Firefox and Opera. */
        border: none;
        /* Needs to be in here for Safari polyfill so background images work as expected. */
        background-size: auto;
    }
    progress:not([value]), progress:not([value])::-webkit-progress-bar {
        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);
    }
    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {
        background: #F44336;
    }
</style>

<table class="dataframe" data-quarto-postprocess="true" data-border="1">
<thead>
<tr style="text-align: left;">
<th data-quarto-table-cell-role="th">epoch</th>
<th data-quarto-table-cell-role="th">train_loss</th>
<th data-quarto-table-cell-role="th">valid_loss</th>
<th data-quarto-table-cell-role="th">mix_gaussian_loss</th>
<th data-quarto-table-cell-role="th">kld</th>
<th data-quarto-table-cell-role="th">time</th>
</tr>
</thead>
<tbody>
<tr>
<td>0</td>
<td>-2.324830</td>
<td>-2.338405</td>
<td>-2.349152</td>
<td>107.466675</td>
<td>01:09</td>
</tr>
<tr>
<td>1</td>
<td>-2.338842</td>
<td>-2.340303</td>
<td>-2.345047</td>
<td>47.436031</td>
<td>01:10</td>
</tr>
<tr>
<td>2</td>
<td>-2.339993</td>
<td>-2.337490</td>
<td>-2.341151</td>
<td>36.604542</td>
<td>01:10</td>
</tr>
<tr>
<td>3</td>
<td>-2.337698</td>
<td>-2.346305</td>
<td>-2.349505</td>
<td>32.004436</td>
<td>01:10</td>
</tr>
<tr>
<td>4</td>
<td>-2.342737</td>
<td>-2.319283</td>
<td>-2.322044</td>
<td>27.611586</td>
<td>01:10</td>
</tr>
<tr>
<td>5</td>
<td>-2.343880</td>
<td>-2.324024</td>
<td>-2.326623</td>
<td>25.985027</td>
<td>01:10</td>
</tr>
<tr>
<td>6</td>
<td>-2.344337</td>
<td>-2.348159</td>
<td>-2.350667</td>
<td>25.081089</td>
<td>01:10</td>
</tr>
<tr>
<td>7</td>
<td>-2.343842</td>
<td>-2.349709</td>
<td>-2.352086</td>
<td>23.770494</td>
<td>01:11</td>
</tr>
<tr>
<td>8</td>
<td>-2.345186</td>
<td>-2.352701</td>
<td>-2.355143</td>
<td>24.418821</td>
<td>01:10</td>
</tr>
<tr>
<td>9</td>
<td>-2.355095</td>
<td>-2.356360</td>
<td>-2.358828</td>
<td>24.684273</td>
<td>01:09</td>
</tr>
<tr>
<td>10</td>
<td>-2.358190</td>
<td>-2.361038</td>
<td>-2.363501</td>
<td>24.632402</td>
<td>01:11</td>
</tr>
<tr>
<td>11</td>
<td>-2.362531</td>
<td>-2.362979</td>
<td>-2.365445</td>
<td>24.661421</td>
<td>01:11</td>
</tr>
<tr>
<td>12</td>
<td>-2.357859</td>
<td>-2.363399</td>
<td>-2.365850</td>
<td>24.508953</td>
<td>01:10</td>
</tr>
<tr>
<td>13</td>
<td>-2.358759</td>
<td>-2.363714</td>
<td>-2.366147</td>
<td>24.336988</td>
<td>01:10</td>
</tr>
<tr>
<td>14</td>
<td>-2.360825</td>
<td>-2.363775</td>
<td>-2.366217</td>
<td>24.420610</td>
<td>01:10</td>
</tr>
<tr>
<td>15</td>
<td>-2.355404</td>
<td>-2.363865</td>
<td>-2.366307</td>
<td>24.411386</td>
<td>01:10</td>
</tr>
</tbody>
</table>

![](0_training_FBM_files/figure-commonmark/cell-26-output-3.png)

![](0_training_FBM_files/figure-commonmark/cell-26-output-4.png)

We save the model after each cycle, just in case all the neurons
collapse due to a big *β*.

``` python
E=64+16; model_name = 'fbm' + f'_E{E}'
if not os.path.exists("./models/"+model_name+'.tar'):
    save_model("./models/"+model_name, model, model_args, ds_args)
```

    Saved at ./models/fbm_E80.tar

Then, we increase the *β* and train again.

``` python
learn.loss_func.beta=6e-4; model_args.update(dict(beta=6e-4))
```

``` python
learn.fit_one_cycle(16, lr_max=1e-3,)
```

<style>
    /* Turns off some styling */
    progress {
        /* gets rid of default border in Firefox and Opera. */
        border: none;
        /* Needs to be in here for Safari polyfill so background images work as expected. */
        background-size: auto;
    }
    progress:not([value]), progress:not([value])::-webkit-progress-bar {
        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);
    }
    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {
        background: #F44336;
    }
</style>

<table class="dataframe" data-quarto-postprocess="true" data-border="1">
<thead>
<tr style="text-align: left;">
<th data-quarto-table-cell-role="th">epoch</th>
<th data-quarto-table-cell-role="th">train_loss</th>
<th data-quarto-table-cell-role="th">valid_loss</th>
<th data-quarto-table-cell-role="th">mix_gaussian_loss</th>
<th data-quarto-table-cell-role="th">kld</th>
<th data-quarto-table-cell-role="th">time</th>
</tr>
</thead>
<tbody>
<tr>
<td>0</td>
<td>-2.353231</td>
<td>-2.353524</td>
<td>-2.364641</td>
<td>18.528250</td>
<td>01:09</td>
</tr>
<tr>
<td>1</td>
<td>-2.348532</td>
<td>-2.352497</td>
<td>-2.362990</td>
<td>17.487579</td>
<td>01:10</td>
</tr>
<tr>
<td>2</td>
<td>-2.342875</td>
<td>-2.334392</td>
<td>-2.344330</td>
<td>16.562178</td>
<td>01:11</td>
</tr>
<tr>
<td>3</td>
<td>-2.346903</td>
<td>-2.336486</td>
<td>-2.345794</td>
<td>15.511265</td>
<td>01:10</td>
</tr>
<tr>
<td>4</td>
<td>-2.330870</td>
<td>-2.346205</td>
<td>-2.356031</td>
<td>16.375021</td>
<td>01:10</td>
</tr>
<tr>
<td>5</td>
<td>-2.349575</td>
<td>-2.353170</td>
<td>-2.362580</td>
<td>15.683105</td>
<td>01:10</td>
</tr>
<tr>
<td>6</td>
<td>-2.347398</td>
<td>-2.351249</td>
<td>-2.360387</td>
<td>15.228333</td>
<td>01:11</td>
</tr>
<tr>
<td>7</td>
<td>-2.345601</td>
<td>-2.350861</td>
<td>-2.359752</td>
<td>14.819258</td>
<td>01:10</td>
</tr>
<tr>
<td>8</td>
<td>-2.352276</td>
<td>-2.356376</td>
<td>-2.364991</td>
<td>14.358064</td>
<td>01:10</td>
</tr>
<tr>
<td>9</td>
<td>-2.356200</td>
<td>-2.355854</td>
<td>-2.364318</td>
<td>14.105173</td>
<td>01:10</td>
</tr>
<tr>
<td>10</td>
<td>-2.350616</td>
<td>-2.355227</td>
<td>-2.363599</td>
<td>13.954180</td>
<td>01:12</td>
</tr>
<tr>
<td>11</td>
<td>-2.355976</td>
<td>-2.357581</td>
<td>-2.365860</td>
<td>13.798420</td>
<td>01:10</td>
</tr>
<tr>
<td>12</td>
<td>-2.354166</td>
<td>-2.357984</td>
<td>-2.366087</td>
<td>13.504392</td>
<td>01:10</td>
</tr>
<tr>
<td>13</td>
<td>-2.359440</td>
<td>-2.358157</td>
<td>-2.366241</td>
<td>13.472176</td>
<td>01:10</td>
</tr>
<tr>
<td>14</td>
<td>-2.343340</td>
<td>-2.358246</td>
<td>-2.366287</td>
<td>13.400112</td>
<td>01:10</td>
</tr>
<tr>
<td>15</td>
<td>-2.365923</td>
<td>-2.358313</td>
<td>-2.366364</td>
<td>13.418869</td>
<td>01:10</td>
</tr>
</tbody>
</table>

![](0_training_FBM_files/figure-commonmark/cell-29-output-3.png)

![](0_training_FBM_files/figure-commonmark/cell-29-output-4.png)

``` python
E=64+16*2; model_name = 'fbm' + f'_E{E}'
if not os.path.exists("./models/"+model_name+'.tar'):
    save_model("./models/"+model_name, model, model_args, ds_args)
```

    Saved at ./models/fbm_E96.tar

We keep training to noise out the collapsed neurons while maintaining
good reconstruction loss
[`mix_gaussian_loss`](https://GabrielFernandezFernandez.github.io/SPIVAE/source/utils.html#mix_gaussian_loss).

``` python
learn.loss_func.beta=1e-3; model_args.update(dict(beta=1e-3))
```

``` python
learn.fit_one_cycle(16, lr_max=1e-3,)
```

<style>
    /* Turns off some styling */
    progress {
        /* gets rid of default border in Firefox and Opera. */
        border: none;
        /* Needs to be in here for Safari polyfill so background images work as expected. */
        background-size: auto;
    }
    progress:not([value]), progress:not([value])::-webkit-progress-bar {
        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);
    }
    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {
        background: #F44336;
    }
</style>

<table class="dataframe" data-quarto-postprocess="true" data-border="1">
<thead>
<tr style="text-align: left;">
<th data-quarto-table-cell-role="th">epoch</th>
<th data-quarto-table-cell-role="th">train_loss</th>
<th data-quarto-table-cell-role="th">valid_loss</th>
<th data-quarto-table-cell-role="th">mix_gaussian_loss</th>
<th data-quarto-table-cell-role="th">kld</th>
<th data-quarto-table-cell-role="th">time</th>
</tr>
</thead>
<tbody>
<tr>
<td>0</td>
<td>-2.348945</td>
<td>-2.353240</td>
<td>-2.364978</td>
<td>11.738488</td>
<td>01:10</td>
</tr>
<tr>
<td>1</td>
<td>-2.358876</td>
<td>-2.342992</td>
<td>-2.353953</td>
<td>10.961354</td>
<td>01:10</td>
</tr>
<tr>
<td>2</td>
<td>-2.350276</td>
<td>-2.350280</td>
<td>-2.360747</td>
<td>10.466887</td>
<td>01:11</td>
</tr>
<tr>
<td>3</td>
<td>-2.341486</td>
<td>-2.282615</td>
<td>-2.292582</td>
<td>9.966481</td>
<td>01:11</td>
</tr>
<tr>
<td>4</td>
<td>-2.342745</td>
<td>-2.343670</td>
<td>-2.353052</td>
<td>9.381420</td>
<td>01:10</td>
</tr>
<tr>
<td>5</td>
<td>-2.345502</td>
<td>-2.333569</td>
<td>-2.343357</td>
<td>9.788860</td>
<td>01:10</td>
</tr>
<tr>
<td>6</td>
<td>-2.361416</td>
<td>-2.354589</td>
<td>-2.363912</td>
<td>9.322714</td>
<td>01:10</td>
</tr>
<tr>
<td>7</td>
<td>-2.350763</td>
<td>-2.352047</td>
<td>-2.361214</td>
<td>9.165956</td>
<td>01:11</td>
</tr>
<tr>
<td>8</td>
<td>-2.354032</td>
<td>-2.354136</td>
<td>-2.363111</td>
<td>8.974744</td>
<td>01:10</td>
</tr>
<tr>
<td>9</td>
<td>-2.351079</td>
<td>-2.355446</td>
<td>-2.364451</td>
<td>9.005571</td>
<td>01:10</td>
</tr>
<tr>
<td>10</td>
<td>-2.348526</td>
<td>-2.355358</td>
<td>-2.364368</td>
<td>9.010308</td>
<td>01:10</td>
</tr>
<tr>
<td>11</td>
<td>-2.349510</td>
<td>-2.355702</td>
<td>-2.364724</td>
<td>9.022109</td>
<td>01:10</td>
</tr>
<tr>
<td>12</td>
<td>-2.359064</td>
<td>-2.356081</td>
<td>-2.365134</td>
<td>9.052643</td>
<td>01:10</td>
</tr>
<tr>
<td>13</td>
<td>-2.358692</td>
<td>-2.356183</td>
<td>-2.365181</td>
<td>8.999000</td>
<td>01:10</td>
</tr>
<tr>
<td>14</td>
<td>-2.357382</td>
<td>-2.356289</td>
<td>-2.365324</td>
<td>9.035031</td>
<td>01:10</td>
</tr>
<tr>
<td>15</td>
<td>-2.347834</td>
<td>-2.356310</td>
<td>-2.365310</td>
<td>9.001582</td>
<td>01:11</td>
</tr>
</tbody>
</table>

![](0_training_FBM_files/figure-commonmark/cell-32-output-3.png)

![](0_training_FBM_files/figure-commonmark/cell-32-output-4.png)

``` python
E=64+16*3; model_name = 'fbm' + f'_E{E}'
if not os.path.exists("./models/"+model_name+'.tar'):
    save_model("./models/"+model_name, model, model_args, ds_args)
```

    Saved at ./models/fbm_E112.tar

``` python
learn.loss_func.beta=2e-3; model_args.update(dict(beta=2e-3))
```

``` python
learn.fit_one_cycle(16, lr_max=1e-3,)
```

<style>
    /* Turns off some styling */
    progress {
        /* gets rid of default border in Firefox and Opera. */
        border: none;
        /* Needs to be in here for Safari polyfill so background images work as expected. */
        background-size: auto;
    }
    progress:not([value]), progress:not([value])::-webkit-progress-bar {
        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);
    }
    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {
        background: #F44336;
    }
</style>

<table class="dataframe" data-quarto-postprocess="true" data-border="1">
<thead>
<tr style="text-align: left;">
<th data-quarto-table-cell-role="th">epoch</th>
<th data-quarto-table-cell-role="th">train_loss</th>
<th data-quarto-table-cell-role="th">valid_loss</th>
<th data-quarto-table-cell-role="th">mix_gaussian_loss</th>
<th data-quarto-table-cell-role="th">kld</th>
<th data-quarto-table-cell-role="th">time</th>
</tr>
</thead>
<tbody>
<tr>
<td>0</td>
<td>-2.350208</td>
<td>-2.348301</td>
<td>-2.362810</td>
<td>7.254685</td>
<td>01:10</td>
</tr>
<tr>
<td>1</td>
<td>-2.337677</td>
<td>-2.346455</td>
<td>-2.359850</td>
<td>6.697080</td>
<td>01:11</td>
</tr>
<tr>
<td>2</td>
<td>-2.345940</td>
<td>-2.336791</td>
<td>-2.349714</td>
<td>6.461686</td>
<td>01:11</td>
</tr>
<tr>
<td>3</td>
<td>-2.339710</td>
<td>-2.338348</td>
<td>-2.351251</td>
<td>6.451570</td>
<td>01:10</td>
</tr>
<tr>
<td>4</td>
<td>-2.344926</td>
<td>-2.340880</td>
<td>-2.353410</td>
<td>6.265362</td>
<td>01:11</td>
</tr>
<tr>
<td>5</td>
<td>-2.349301</td>
<td>-2.347707</td>
<td>-2.359997</td>
<td>6.144722</td>
<td>01:11</td>
</tr>
<tr>
<td>6</td>
<td>-2.336591</td>
<td>-2.344263</td>
<td>-2.356583</td>
<td>6.159823</td>
<td>01:10</td>
</tr>
<tr>
<td>7</td>
<td>-2.345398</td>
<td>-2.346607</td>
<td>-2.358751</td>
<td>6.072074</td>
<td>01:10</td>
</tr>
<tr>
<td>8</td>
<td>-2.342644</td>
<td>-2.346272</td>
<td>-2.358593</td>
<td>6.160376</td>
<td>01:10</td>
</tr>
<tr>
<td>9</td>
<td>-2.345847</td>
<td>-2.348051</td>
<td>-2.360079</td>
<td>6.013485</td>
<td>01:11</td>
</tr>
<tr>
<td>10</td>
<td>-2.351193</td>
<td>-2.349379</td>
<td>-2.361663</td>
<td>6.141795</td>
<td>01:10</td>
</tr>
<tr>
<td>11</td>
<td>-2.350389</td>
<td>-2.349450</td>
<td>-2.361586</td>
<td>6.067914</td>
<td>01:10</td>
</tr>
<tr>
<td>12</td>
<td>-2.351185</td>
<td>-2.349608</td>
<td>-2.361853</td>
<td>6.122767</td>
<td>01:10</td>
</tr>
<tr>
<td>13</td>
<td>-2.344490</td>
<td>-2.349607</td>
<td>-2.361763</td>
<td>6.078405</td>
<td>01:10</td>
</tr>
<tr>
<td>14</td>
<td>-2.347708</td>
<td>-2.349838</td>
<td>-2.362053</td>
<td>6.107482</td>
<td>01:11</td>
</tr>
<tr>
<td>15</td>
<td>-2.342868</td>
<td>-2.349836</td>
<td>-2.362056</td>
<td>6.109914</td>
<td>01:10</td>
</tr>
</tbody>
</table>

![](0_training_FBM_files/figure-commonmark/cell-35-output-3.png)

![](0_training_FBM_files/figure-commonmark/cell-35-output-4.png)

``` python
E=64+16*4; model_name = 'fbm' + f'_E{E}'
if not os.path.exists("./models/"+model_name+'.tar'):
    save_model("./models/"+model_name, model, model_args, ds_args)
```

    Saved at ./models/fbm_E128.tar

``` python
learn.loss_func.beta=4e-3; model_args.update(dict(beta=4e-3))
```

``` python
learn.fit_one_cycle(16, lr_max=1e-3,)
```

<style>
    /* Turns off some styling */
    progress {
        /* gets rid of default border in Firefox and Opera. */
        border: none;
        /* Needs to be in here for Safari polyfill so background images work as expected. */
        background-size: auto;
    }
    progress:not([value]), progress:not([value])::-webkit-progress-bar {
        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);
    }
    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {
        background: #F44336;
    }
</style>

<table class="dataframe" data-quarto-postprocess="true" data-border="1">
<thead>
<tr style="text-align: left;">
<th data-quarto-table-cell-role="th">epoch</th>
<th data-quarto-table-cell-role="th">train_loss</th>
<th data-quarto-table-cell-role="th">valid_loss</th>
<th data-quarto-table-cell-role="th">mix_gaussian_loss</th>
<th data-quarto-table-cell-role="th">kld</th>
<th data-quarto-table-cell-role="th">time</th>
</tr>
</thead>
<tbody>
<tr>
<td>0</td>
<td>-2.344279</td>
<td>-2.338168</td>
<td>-2.358795</td>
<td>5.156413</td>
<td>01:10</td>
</tr>
<tr>
<td>1</td>
<td>-2.345974</td>
<td>-2.335615</td>
<td>-2.355980</td>
<td>5.091214</td>
<td>01:14</td>
</tr>
<tr>
<td>2</td>
<td>-2.328641</td>
<td>-2.337625</td>
<td>-2.357382</td>
<td>4.939382</td>
<td>01:11</td>
</tr>
<tr>
<td>3</td>
<td>-2.320290</td>
<td>-2.328844</td>
<td>-2.348158</td>
<td>4.828393</td>
<td>01:11</td>
</tr>
<tr>
<td>4</td>
<td>-2.326955</td>
<td>-2.337008</td>
<td>-2.356167</td>
<td>4.790024</td>
<td>01:11</td>
</tr>
<tr>
<td>5</td>
<td>-2.326622</td>
<td>-2.334390</td>
<td>-2.353814</td>
<td>4.856228</td>
<td>01:10</td>
</tr>
<tr>
<td>6</td>
<td>-2.328627</td>
<td>-2.337150</td>
<td>-2.356401</td>
<td>4.812714</td>
<td>01:11</td>
</tr>
<tr>
<td>7</td>
<td>-2.324614</td>
<td>-2.339001</td>
<td>-2.358472</td>
<td>4.867772</td>
<td>01:11</td>
</tr>
<tr>
<td>8</td>
<td>-2.321634</td>
<td>-2.339200</td>
<td>-2.358446</td>
<td>4.811536</td>
<td>01:10</td>
</tr>
<tr>
<td>9</td>
<td>-2.346042</td>
<td>-2.339435</td>
<td>-2.358616</td>
<td>4.795233</td>
<td>01:10</td>
</tr>
<tr>
<td>10</td>
<td>-2.342316</td>
<td>-2.339132</td>
<td>-2.358153</td>
<td>4.755326</td>
<td>01:11</td>
</tr>
<tr>
<td>11</td>
<td>-2.333755</td>
<td>-2.339544</td>
<td>-2.358423</td>
<td>4.719747</td>
<td>01:10</td>
</tr>
<tr>
<td>12</td>
<td>-2.331389</td>
<td>-2.339730</td>
<td>-2.358924</td>
<td>4.798558</td>
<td>01:10</td>
</tr>
<tr>
<td>13</td>
<td>-2.339941</td>
<td>-2.339780</td>
<td>-2.358954</td>
<td>4.793717</td>
<td>01:11</td>
</tr>
<tr>
<td>14</td>
<td>-2.335042</td>
<td>-2.339912</td>
<td>-2.359108</td>
<td>4.799071</td>
<td>01:11</td>
</tr>
<tr>
<td>15</td>
<td>-2.337263</td>
<td>-2.339907</td>
<td>-2.359071</td>
<td>4.790753</td>
<td>01:10</td>
</tr>
</tbody>
</table>

![](0_training_FBM_files/figure-commonmark/cell-38-output-3.png)

![](0_training_FBM_files/figure-commonmark/cell-38-output-4.png)

``` python
E=64+16*5; model_name = 'fbm' + f'_E{E}'
if not os.path.exists("./models/"+model_name+'.tar'):
    save_model("./models/"+model_name, model, model_args, ds_args)
```

    Saved at ./models/fbm_E144.tar

After training, we observe a good reconstruction loss around -2.36,
while the *D*<sub>*K**L*</sub> is on the order of one for two neurons
and the rest are three orders of magnitude below. We say that two
neurons *survive* while the rest are noised out. We will see in the
[analysis tutorial](analysis_fbm.html) how these two neurons encode the
minimal relevant information to generate the trajectories.
