project:
  type: website
  output-dir: _docs
# help LLMs as explained in https://llmstxt.org/nbdev.html#configuration 
  pre-render:
    - pysym2md --output_file apilist.txt nbdev
  post-render:
    - llms_txt2ctx llms.txt --optional true --save_nbdev_fname llms-ctx-full.txt
    - llms_txt2ctx llms.txt --save_nbdev_fname llms-ctx.txt
  resources:
    - "*.txt"

format:
  commonmark: default
  html:
    keep-md: true
    page-layout: full
    respect-user-color-scheme: true
    theme:
      dark: darkly
      light: lumen
    css: styles.css
    include-after-body: fix-commonmark.html
    mainfont: "Libertinus Sans"
    monofont: "Libertinus Mono"
    toc: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-tools:
      source: true
      toggle: true
    fig-align: center
    lightbox: true
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true

language: 
  search-text-placeholder: "Search"

website:
  title: "SPIVAE"
  site-url: "https://GabrielFernandezFernandez.github.io/SPIVAE"
  description: "Stochastic processes insights from VAE. Code for the paper: Learning minimal representations of stochastic processes with variational autoencoders."
  repo-branch: main
  repo-url: "https://github.com/GabrielFernandezFernandez/SPIVAE"
  favicon: spivae_icon.png
  twitter-card: true
  open-graph: true
  repo-actions: [source]
  back-to-top-navigation: true
  page-navigation: true
  bread-crumbs: false
  
 # navbar:
 #   background: primary
 #   search: true
 #   right:
 #     - icon: github
 #       href: "https://github.com/GabrielFernandezFernandez/SPIVAE"

  sidebar:
    style: floating
    search: true
    contents:
    #- index.ipynb
    - section: Documentation
      contents:
      - source/00_data.ipynb
      - source/01_models.ipynb
      - source/02_utils.ipynb
    - section: Tutorials
      contents:
      - section: Fractional Brownian motion
        contents:
        - tutorials/0_training_FBM.ipynb
        - tutorials/1_analysis_FBM.ipynb
        - tutorials/2_generation_FBM.ipynb
      - section: Scaled Brownian motion
        contents:
        - tutorials/0_training_SBM.ipynb
        - tutorials/1_analysis_SBM.ipynb
        - tutorials/2_generation_SBM.ipynb

  page-footer: 
    center: "© 2023 onwards, Gabriel Fernández Fernández"
    border: false
        
# we use a single file 
# metadata-files: [nbdev.yml, sidebar.yml]